services:
  mongo:
    container_name: mongo-container
    image: mongo:6
    restart: always
    volumes:
      - ./data:/data/db
    ports: 
      - "27017:27017"
  api:
    container_name: api-container
    restart: always
    image: node:20
    working_dir: /usr/workspace/node-api-ts
    command: bash -c "npm install --omit=dev && npm run debug"
    volumes: 
      - ./dist/:/usr/workspace/node-api-ts/dist/
      - ./package.json:/usr/workspace/node-api-ts/package.json
    ports: 
    - "5050:5050"
    - "9222:9222"
    links: 
      - mongo
